-- +goose Up
ALTER TABLE properties
ALTER COLUMN id SET NOT NULL,
ALTER COLUMN bedrooms SET NOT NULL,
ALTER COLUMN bathrooms SET NOT NULL,
ALTER COLUMN description SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN latitude SET NOT NULL,
ALTER COLUMN longitude SET NOT NULL,
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN listing_update_reason SET NOT NULL,
ALTER COLUMN listing_update_date SET NOT NULL,
ALTER COLUMN price_amount SET NOT NULL,
ALTER COLUMN price_currency_code SET NOT NULL,
ALTER COLUMN estate_agent_telephone SET NOT NULL,
ALTER COLUMN estate_agent_name SET NOT NULL,
ALTER COLUMN created_at SET NOT NULL;

-- +goose Down
ALTER TABLE properties
ALTER COLUMN id DROP NOT NULL,
ALTER COLUMN bedrooms DROP NOT NULL,
ALTER COLUMN bathrooms DROP NOT NULL,
ALTER COLUMN description DROP NOT NULL,
ALTER COLUMN address DROP NOT NULL,
ALTER COLUMN latitude DROP NOT NULL,
ALTER COLUMN longitude DROP NOT NULL,
ALTER COLUMN type DROP NOT NULL,
ALTER COLUMN listing_update_reason DROP NOT NULL,
ALTER COLUMN listing_update_date DROP NOT NULL,
ALTER COLUMN price_amount DROP NOT NULL,
ALTER COLUMN price_currency_code DROP NOT NULL,
ALTER COLUMN estate_agent_telephone DROP NOT NULL,
ALTER COLUMN estate_agent_name DROP NOT NULL,
ALTER COLUMN created_at DROP NOT NULL;
