// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Property struct {
	Bedrooms             int32
	Bathrooms            int32
	Description          string
	Address              string
	Latitude             float64
	Longitude            float64
	Type                 string
	ListingUpdateReason  string
	ListingUpdateDate    time.Time
	PriceAmount          int32
	PriceCurrencyCode    string
	EstateAgentTelephone string
	EstateAgentName      string
	CreatedAt            time.Time
	ID                   int32
}
